#!/usr/bin/env python3

# Algoritmia básica - Práctica 2
# Nicolás de Rivas (843740)
# Cristina Embid (842102)

import imageio as iio
import numpy as np
from costuras import *
import sys
import logging

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.DEBUG,
        filename="tiempos.log",
        filemode="a",
    )
    # Verificar número de argumentos
    if len(sys.argv) != 4:
        print("Uso: costuras <n> <archivo> <salida>")
        exit(1)
    # Número de costuras a eliminar
    n = int(sys.argv[1])
    # Leer la imagen de entrada
    img = iio.imread(sys.argv[2])
    if (n < 1 or n > img.shape[1]):
        print("No se pueden quitar ", n, " costuras en una imagen de anchura ", img.shape[1])
    # Ajustar límite de recursión para evitar fallos en imágenes
    sys.setrecursionlimit(img.shape[0] * img.shape[1])
    # Elimina <n> costuras de la imagen
    for i in range(n):
        costura = encontrarCostura(img)
        print(i+1, "/", n)
        img = quitarCostura(costura, img)
        iio.imwrite(sys.argv[3]+"/"+sys.argv[2]+"_it"+str(i)+".bmp", img)  # Guarda la imagen resultante
    exit(0)
