#!/usr/bin/env python3

# Algoritmia básica - Práctica 2
# Nicolás de Rivas (843740)
# Cristina Embid (842102)

import imageio as iio
import numpy as np
from Costurero import *

from timer import timer
import sys
import logging

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.DEBUG,
        filename="tiempos.log",
        filemode="a",
    )
    # Verificar número de argumentos
    if len(sys.argv) != 4:
        print("Uso: costuras <n> <archivo> <salida>")
        exit(1)
    # Número de costuras a eliminar
    n = int(sys.argv[1])
    costurero = Costurero(sys.argv[2])
    print("1 /", n)
    costurero.guardarImagen(sys.argv[3] + "/" + sys.argv[2] + "_it0.bmp")
    # Leer la imagen de entrada
    if n < 1 or n >= costurero.img.shape[1]:
        print(
            "No se pueden quitar ",
            n,
            " costuras en una imagen de anchura ",
            costurero.img.shape[1],
        )
    # Ajustar límite de recursión para evitar fallos en imágenes
    sys.setrecursionlimit(costurero.img.shape[0] * costurero.img.shape[1])
    # Elimina <n> costuras de la imagen
    for i in range(1, n):
        costurero.calcularCostura()
        print(i + 1, "/", n)
        costurero.guardarImagen(
            sys.argv[3] + "/" + sys.argv[2] + "_it" + str(i + 1) + ".bmp"
        )
    exit(0)
